# -*- coding: utf-8 -*-
"""241112

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nYFFr_1A1yC3x3WpZXW8Lm5s3F55LqH
"""

import sys
sys.stdin = open("input.txt", "r")  # 파일을 읽기 위해 sys.stdin을 설정

T = int(sys.stdin.readline())

for test_case in range(1, T + 1):
    b = 0
    a = list(map(int, sys.stdin.readline().split()))  # 한 줄씩 읽어오기
    for num in a:
        if num % 2 != 0:
            b += num
    print("#%d %d" % (test_case, b), end=" \n")

""" **한줄에 홀수만 읽어서추가**"""