# -*- coding: utf-8 -*-
"""241112

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nYFFr_1A1yC3x3WpZXW8Lm5s3F55LqH
"""

import sys
sys.stdin = open("input.txt", "r")  # 파일을 읽기 위해 sys.stdin을 설정

T = int(sys.stdin.readline())

for test_case in range(1, T + 1):
    b = 0
    a = list(map(int, sys.stdin.readline().split()))  # 한 줄씩 읽어오기
    for num in a:
        if num % 2 != 0:
            b += num
    print("#%d %d" % (test_case, b), end=" \n")

"""2072. 홀수만 더하기"""

import sys
sys.stdin = open("input(1).txt", "r")

T = int(sys.stdin.readline())
# 여러개의 테스트 케이스가 주어지므로, 각각을 처리합니다.
for test_case in range(1, T + 1):
    # ///////////////////////////////////////////////////////////////////////////////////
    N = int(sys.stdin.readline()) #N일
    prices = list(map(int, sys.stdin.readline().split()))  # 각 날의 매매가 리스트

    max_profit = 0 # 최대 이익 초기화
    max_price = 0 # 최대 가격 초기화

    # 뒤에서 부터 탐색
    for price in reversed(prices):
      if price > max_price:
        max_price = price
      max_profit += max_price - price

    print(f'#{test_case} {max_profit}')
    import sys
    # ///////////////////////////////////////////////////////////////////////////////////

"""1859. 백만 장자 프로젝트"""
